### ISSUE TITLE
read.asc error

### ISSUE THREAD

**Issue by george-farmer** [dahtah/eyelinker#2]
Hi Simon, thanks for the package, it looks great. The issue is I get an error when trying to read in an asc file:

```
> dat <- read.asc('Data/Matrix2.asc')
Error in vector(type, length) : 
  vector: cannot make a vector of mode 'NULL'.
> traceback()
8: vector(type, length)
7: allocate_column(df[[var]], nrows, dfs, var)
6: output_template(dfs, nrows)
5: rbind.fill(res)
4: list_to_dataframe(res, attr(.data, "split_labels"), .id, id_as_factor)
3: ldply(valid, function(ind) mutate(blocks[[ind]][[vname]], block = ind))
2: collect("raw")
1: read.asc("Data/Matrix2.asc")
```

I have tried a few different asc files, but always the same error. Any ideas? Thanks.
George

[Matrix2.zip](https://github.com/dahtah/eyelinker/files/274584/Matrix2.zip)

**Comment by dahtah** [comment]
Hi George. Congratulations, you've found a bug - it's related to the head target information (your samples are all labelled as "target too close", which the parser wasn't expecting). Should be fixed, can you please reinstall and test?
`install_github("dahtah/eyelinker")`

**Comment by george-farmer** [comment]
All working fine now. Thanks very much!
